#!/usr/bin/env php
<?php

require_once '../_config.php';

$restClient = new \Sirprize\Rest\Client($config);
$restClient->setCache($cache);

$service = new \Sirprize\Flickr\Service($config);
$service->setRestClient($restClient);

$userId = new \Sirprize\Flickr\Id(FLICKR_NSID);

$observerStout = new \Sirprize\Flickr\Core\Collection\Observer();

$photoSets = $service->getPhotoSetsInstance();
$photoSets->attachObserver($observerStout);
$photoSets->startAllByUserId($userId);

foreach($photoSets as $photoSet)
{
	$photoSet->getPhotos()->startByPhotoSetId($photoSet->getId());
	
	print $photoSet->getTitle()."\n";
	
	foreach($photoSet->getPhotos() as $photo)
	{
		print "    ".$photo->getTitle()."\n";
		print "        ".$photo->getSizes()->getOriginalUrl()."\n";
	}
}