#!/usr/bin/env php
<?php

require_once '../_config.php';

$restClient = new \Sirprize\Rest\Client($config);
$restClient->setCache($cache);

$service = new \Sirprize\Flickr\Service($config);
$service->setRestClient($restClient);

$userId = new \Sirprize\Flickr\Id(FLICKR_NSID);

$observerStout = new \Sirprize\Flickr\Core\Collection\Observer();

$collections = $service->getCollectionsInstance();
$collections->attachObserver($observerStout);
$collections->startAllByUserId($userId);

foreach($collections as $collection)
{
	print $collection->getTitle()." - ".$collection->getId()."\n";
	
	foreach($collection->getPhotoSets() as $photoSet)
	{
		print "    ".$photoSet->getTitle()."\n";
		
		$photoSet->getPhotos()->startByPhotoSetId($photoSet->getId());
		
		foreach($photoSet->getPhotos() as $photo)
		{
			print "        ".$photo->getTitle()."\n";
			print "            ".$photo->getSizes()->getOriginalSource()."\n";
			print "            ".$photo->getSizes()->getOriginalUrl()."\n";
			print "            ".$photo->getSizes()->getMediumSource()."\n";
			print "            ".$photo->getSizes()->getMediumUrl()."\n";
		}
	}
}